{% set name = "parcel" %}
{% set version = "2.14.0" %}

package:
  name: {{ name }}js
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 9a67728bd00214a3bc2f4e8573e464467d902623a15433e9cc6712b807c35b3f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - node-gyp
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - parcel --help

about:
  home: https://github.com/parcel-bundler/parcel
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Blazing fast, zero configuration web application bundler

extra:
  recipe-maintainers:
    - xhochy
