{% set name = "parcel" %}
{% set version = "2.10.2" %}

package:
  name: {{ name }}js
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 4d17890827f48cb1b07cecb3a1ba793df93f7cfa1b2d7a3c525b992e512f0545

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - node-gyp
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - parcel --help

about:
  home: https://github.com/parcel-bundler/parcel
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Blazing fast, zero configuration web application bundler

extra:
  recipe-maintainers:
    - xhochy
