{% set name = "parcel" %}
{% set version = "2.16.2" %}

package:
  name: {{ name }}js
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: c98fd3931cc40fab218e2bbf40c87792e36b3707af5bb7d3e662c444c4925cb1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - node-gyp
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - parcel --help

about:
  home: https://github.com/parcel-bundler/parcel
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Blazing fast, zero configuration web application bundler

extra:
  recipe-maintainers:
    - xhochy
