{% set name = "parcel" %}
{% set version = "2.16.3" %}

package:
  name: {{ name }}js
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: a03ee0a89d6b05f376f089e059812be2f036cc9446fe590b040f80b07d6d35bb

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - node-gyp
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - parcel --help

about:
  home: https://github.com/parcel-bundler/parcel
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Blazing fast, zero configuration web application bundler

extra:
  recipe-maintainers:
    - xhochy
