{% set name = "parcel" %}
{% set version = "2.16.1" %}

package:
  name: {{ name }}js
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 9cccba0f5b30a1af1954f8de423888bf80aae5a8f73df5d5e9e1c1c48cd2e039

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - node-gyp
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - parcel --help

about:
  home: https://github.com/parcel-bundler/parcel
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Blazing fast, zero configuration web application bundler

extra:
  recipe-maintainers:
    - xhochy
